import { Inject, Injectable } from '@nestjs/common';
import { Tenant } from '../../../domain/tenant/entities/tenant.entity';
import { ITenantRepository, TENANT_REPOSITORY } from '../../../domain/ports/out/tenant-repository.port';
import { CreateTenantCommand } from '../../ports/in/commands/create-tenant.command';

@Injectable()
export class CreateTenantUseCase {
    constructor(
        @Inject(TENANT_REPOSITORY)
        private readonly tenantRepository: ITenantRepository,
    ) { }

    async execute(command: CreateTenantCommand): Promise<Tenant> {
        const tenant = new Tenant(
            '', // ID will be generated by database
            command.name,
            command.subdomain,
            command.status || 'active',
            command.plan || 'free',
        );

        return await this.tenantRepository.create(tenant);
    }
}
