import { Inject, Injectable } from '@nestjs/common';
import { Tenant } from '../../../domain/tenant/entities/tenant.entity';
import { ITenantRepository, TENANT_REPOSITORY } from '../../../domain/ports/out/tenant-repository.port';

export interface CreateTenantCommand {
    name: string;
    subdomain: string;
    plan?: 'free' | 'basic' | 'premium' | 'enterprise';
    status?: 'active' | 'suspended' | 'inactive';
}

@Injectable()
export class CreateTenantUseCase {
    constructor(
        @Inject(TENANT_REPOSITORY)
        private readonly tenantRepository: ITenantRepository,
    ) { }

    async execute(command: CreateTenantCommand): Promise<Tenant> {
        const tenant = new Tenant(
            '', // ID will be generated by database
            command.name,
            command.subdomain,
            command.status || 'active',
            command.plan || 'free',
        );

        return await this.tenantRepository.create(tenant);
    }
}
