export interface CreateTenantCommand {
    name: string;
    /** Optional custom subdomain; when omitted, we derive and ensure uniqueness */
    subdomain?: string;
    contactEmail: string;
    contactPhone?: string;
    address?: {
        street?: string;
        city?: string;
        state?: string;
        postalCode?: string;
        country?: string;
    };
    branding?: {
        logo?: string;
        favicon?: string;
        primaryColor?: string;
        secondaryColor?: string;
        accentColor?: string;
        customDomain?: string;
    };
    ownerId?: string;
    /** Optional edition code (legacy). Prefer `editionId` when available. */
    edition?: string;
    /** Optional edition id (preferred). */
    editionId?: string;
    /** Optional metadata to attach to tenant creation */
    metadata?: Record<string, any>;
    status?: 'pending' | 'active' | 'suspended' | 'inactive';
    /** Optional pre-generated school code; otherwise generated by the use case */
    schoolId?: string;
    locale?: string;
    timezone?: string;
    weekStartsOn?: 'monday' | 'sunday';
    limits?: {
        maxStudents?: number;
        maxTeachers?: number;
        maxClasses?: number;
        maxAdmins?: number;
        maxStorage?: number;
        maxBandwidth?: number;
    };
    academicYear?: {
        start: Date | string;
        end: Date | string;
        name?: string;
    };
    adminName: string;
    adminEmail: string;
    /** If omitted, a strong temporary password will be generated */
    adminPassword?: string;
}
