export interface CreateTenantCommand {
    name: string;
    /** Optional custom subdomain; when omitted, we derive and ensure uniqueness */
    subdomain?: string;
    contactEmail: string;
    contactPhone?: string;
    address?: {
        street?: string;
        city?: string;
        state?: string;
        postalCode?: string;
        country?: string;
    };
    logo?: string;
    ownerId?: string;
    plan?: 'trial' | 'free' | 'basic' | 'premium' | 'enterprise';
    status?: 'pending' | 'active' | 'suspended' | 'inactive';
    /** Optional pre-generated school code; otherwise generated by the use case */
    schoolId?: string;
    locale?: string;
    timezone?: string;
    weekStartsOn?: 'monday' | 'sunday';
    academicYear?: {
        start: Date | string;
        end: Date | string;
        name?: string;
    };
    adminName: string;
    adminEmail: string;
    /** If omitted, a strong temporary password will be generated */
    adminPassword?: string;
}
