export class Tenant {
    constructor(
        public readonly id: string,
        public readonly name: string,
        public readonly subdomain: string,
        public readonly status: 'active' | 'suspended' | 'inactive',
        public readonly plan: 'free' | 'basic' | 'premium' | 'enterprise',
        public readonly settings?: TenantSettings,
        public readonly createdAt?: Date,
        public readonly updatedAt?: Date,
    ) { }

    static create(props: Omit<Tenant, 'id' | 'createdAt' | 'updatedAt'>): Tenant {
        return new Tenant(
            '', // ID will be generated by the database
            props.name,
            props.subdomain,
            props.status || 'active',
            props.plan || 'free',
            props.settings,
        );
    }

    isActive(): boolean {
        return this.status === 'active';
    }

    canAccessFeature(feature: string): boolean {
        const featuresByPlan = {
            free: ['basic_features'],
            basic: ['basic_features', 'student_management', 'attendance'],
            premium: ['basic_features', 'student_management', 'attendance', 'finance', 'library'],
            enterprise: ['basic_features', 'student_management', 'attendance', 'finance', 'library', 'hr', 'transport', 'hostel'],
        };

        return featuresByPlan[this.plan]?.includes(feature) || false;
    }
}

export interface TenantSettings {
    maxStudents?: number;
    maxTeachers?: number;
    maxClasses?: number;
    features?: string[];
    customization?: {
        logo?: string;
        primaryColor?: string;
        secondaryColor?: string;
        accentColor?: string;
    };
    locale?: string;
    timezone?: string;
    weekStartsOn?: 'monday' | 'sunday';
    currency?: string;
    academicYear?: {
        start: string; // ISO date
        end: string; // ISO date
    };
}
