import { Edition } from './edition.entity';

/**
 * Canonical platform editions seeded at startup.
 * Keep in sync with scripts/seed-editions.js
 */
export function createGlobalEditions(): Edition[] {
    return [
        Edition.create({
            id: `free-edition`,
            name: 'free',
            displayName: 'Free',
            description: 'Basic features for small schools and evaluation',
            monthlyPrice: 0,
            annualPrice: 0,
            perStudentMonthly: null,
            annualPriceNotes: null,
            isActive: true,
            sortOrder: 10,
            modules: [
                'dashboard',
                'students',
                'attendance',
                'academics',
                'setup',
            ],
        }),
        Edition.create({
            id: `professional-edition`,
            name: 'professional',
            displayName: 'Professional',
            description: 'Most features for small to medium schools',
            monthlyPrice: 99,
            annualPrice: 950,
            perStudentMonthly: null,
            annualPriceNotes: null,
            isActive: true,
            sortOrder: 20,
            modules: [
                'dashboard',
                'students',
                'admissions',
                'attendance',
                'academics',
                'fees',
                'library',
                'roles',
                'tasks',
                'setup',
                'plugins'
            ],
        }),
        Edition.create({
            id: `premium-edition`,
            name: 'premium',
            displayName: 'Premium',
            description: 'Advanced features for multi-school operations',
            monthlyPrice: 299,
            annualPrice: 2870,
            perStudentMonthly: null,
            annualPriceNotes: null,
            isActive: true,
            sortOrder: 30,
            modules: [
                'dashboard',
                'students',
                'admissions',
                'attendance',
                'academics',
                'fees',
                'accounting',
                'finance',
                'hr',
                'library',
                'hostel',
                'transport',
                'roles',
                'tasks',
                'setup',
                'plugins'
            ],
        }),
        Edition.create({
            id: `enterprise-edition`,
            name: 'enterprise',
            displayName: 'Enterprise',
            description: 'Enterprise-grade features and support',
            monthlyPrice: null,
            annualPrice: null,
            perStudentMonthly: 2,
            annualPriceNotes: 'Custom',
            isActive: true,
            sortOrder: 40,
            modules: [
                'dashboard',
                'students',
                'admissions',
                'apply',
                'attendance',
                'academics',
                'fees',
                'accounting',
                'finance',
                'hr',
                'payroll',
                'library',
                'hostel',
                'transport',
                'roles',
                'tasks',
                'setup',
                'plugins'
            ],
        }),
    ];
}
